# Generated by Django 6.1.1 on 2026-09-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaDeCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.CharField(max_length=3)),
                ('data', models.DateField()),
                ('taxa', models.DecimalField(decimal_places=8, max_digits=18)),
                ('fonte', models.CharField(max_length=20)),
                ('obtida_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'taxa_de_cambio',
                'ordering': ['moeda', '-data'],
                'indexes': [models.Index(fields=['moeda', 'data'], name='taxa_de_cam_moeda_a835f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('moeda', 'data', 'fonte'), name='uq_taxa_moeda_data_fonte'), models.CheckConstraint(condition=models.Q(('taxa__gt', 0)), name='ck_taxa_positiva')],
            },
        ),
    ]
