# Generated by Django 6.1.1 on 2026-09-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoDoPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('tirada_em', models.DateTimeField()),
            ],
            options={
                'db_table': 'foto_do_patrimonio',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='ValorDaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=10)),
                ('papel', models.CharField(max_length=20)),
                ('instituicao', models.CharField(max_length=120)),
                ('moeda', models.CharField(max_length=3)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('linhas', models.PositiveIntegerField()),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='consolidado.fotodopatrimonio')),
            ],
            options={
                'db_table': 'valor_da_foto',
                'ordering': ['foto', 'fonte', 'instituicao', 'moeda'],
                'constraints': [models.UniqueConstraint(fields=('foto', 'fonte', 'instituicao', 'moeda'), name='uq_valor_foto_fonte_instituicao_moeda')],
            },
        ),
    ]
